//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chrysallis.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chrysallis.Idiomas.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esdeveniments.
        /// </summary>
        internal static string _event {
            get {
                return ResourceManager.GetString("event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actiu.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Afegir esdeveniments.
        /// </summary>
        internal static string addEvent {
            get {
                return ResourceManager.GetString("addEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Afegir soci.
        /// </summary>
        internal static string addPartner {
            get {
                return ResourceManager.GetString("addPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adreça.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }

        internal static string getComunidad(string nombre)
        {
            return ResourceManager.GetString(nombre, resourceCulture);
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Andalusia.
        /// </summary>
        internal static string Andalucía {
            get {
                return ResourceManager.GetString("Andalucía", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aragó.
        /// </summary>
        internal static string Aragón {
            get {
                return ResourceManager.GetString("Aragón", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canàries.
        /// </summary>
        internal static string Canarias {
            get {
                return ResourceManager.GetString("Canarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantàbria.
        /// </summary>
        internal static string Cantabria {
            get {
                return ResourceManager.GetString("Cantabria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Castella - la Manxa.
        /// </summary>
        internal static string Castilla_La_Mancha {
            get {
                return ResourceManager.GetString("Castilla-La Mancha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Castella i Lleó.
        /// </summary>
        internal static string Castilla_y_León {
            get {
                return ResourceManager.GetString("Castilla y León", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Català.
        /// </summary>
        internal static string catalan {
            get {
                return ResourceManager.GetString("catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalunya.
        /// </summary>
        internal static string Cataluña {
            get {
                return ResourceManager.GetString("Cataluña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ceuta.
        /// </summary>
        internal static string Ceuta {
            get {
                return ResourceManager.GetString("Ceuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona.
        /// </summary>
        internal static string chosse {
            get {
                return ResourceManager.GetString("chosse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunitat.
        /// </summary>
        internal static string community {
            get {
                return ResourceManager.GetString("community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunitat de Madrid.
        /// </summary>
        internal static string Comunidad_de_Madrid {
            get {
                return ResourceManager.GetString("Comunidad de Madrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunitat Foral de Navarra.
        /// </summary>
        internal static string Comunidad_Foral_de_Navarra {
            get {
                return ResourceManager.GetString("Comunidad Foral de Navarra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunitat Valenciana.
        /// </summary>
        internal static string Comunidad_Valenciana {
            get {
                return ResourceManager.GetString("Comunidad Valenciana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunitat.
        /// </summary>
        internal static string comunity {
            get {
                return ResourceManager.GetString("comunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data limit.
        /// </summary>
        internal static string deadline {
            get {
                return ResourceManager.GetString("deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documents.
        /// </summary>
        internal static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correu.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anglès.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extremadura.
        /// </summary>
        internal static string Extremadura {
            get {
                return ResourceManager.GetString("Extremadura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Galícia.
        /// </summary>
        internal static string Galicia {
            get {
                return ResourceManager.GetString("Galicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Illes Balears.
        /// </summary>
        internal static string Islas_Baleares {
            get {
                return ResourceManager.GetString("Islas Baleares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Rioja.
        /// </summary>
        internal static string La_Rioja {
            get {
                return ResourceManager.GetString("La Rioja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cognoms.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicació.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accedir.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar esdeveniments.
        /// </summary>
        internal static string manageEvents {
            get {
                return ResourceManager.GetString("manageEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar socis.
        /// </summary>
        internal static string managePartners {
            get {
                return ResourceManager.GetString("managePartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Melilla.
        /// </summary>
        internal static string Melilla {
            get {
                return ResourceManager.GetString("Melilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nom.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificacions.
        /// </summary>
        internal static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre assistents.
        /// </summary>
        internal static string numberOfAttendees {
            get {
                return ResourceManager.GetString("numberOfAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País Basc.
        /// </summary>
        internal static string País_Vasco {
            get {
                return ResourceManager.GetString("País Vasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soci.
        /// </summary>
        internal static string partner {
            get {
                return ResourceManager.GetString("partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Socis.
        /// </summary>
        internal static string partners {
            get {
                return ResourceManager.GetString("partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasenya.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telèfon.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principat d&apos;Astúries.
        /// </summary>
        internal static string Principado_de_Asturias {
            get {
                return ResourceManager.GetString("Principado de Asturias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regió de Múrcia.
        /// </summary>
        internal static string Región_de_Murcia {
            get {
                return ResourceManager.GetString("Región de Murcia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desar.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Castellà.
        /// </summary>
        internal static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatal.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuari.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
    }
}
